osx_image: beta-xcode6.3
language: objective-c

xcode_workspace: BingAPI_PromiseKit.xcworkspace
xcode_sdk: iphonesimulator8.3

script:
- xcodebuild test -workspace BingAPI_PromiseKit.xcworkspace -scheme 'BingAPI_PromiseKit' -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)'
- xcodebuild -workspace BingAPI_PromiseKit.xcworkspace -scheme 'Podspec Lint' -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)'

env:
    global:
    - TIMEOUT=1000
    matrix:
    - USE_NETWORK=true

